export const AI_NOTICE_VERSION = "2026-10-01";
export const AI_LEGAL_URL = "/legal/contenido-ia";
export const AI_DISCLAIMER = {
  es: {
    title: "Contenido generado con IA y derechos de autor",
    short: "Generado con IA. El contenido creado íntegramente por IA puede no estar protegido por derechos de autor. Revísalo antes de publicar.",
    long: "Contenido generado con inteligencia artificial. Pawwer utiliza herramientas de IA para generar textos, imágenes y videos. Conforme a la legislación de derechos de autor de México y de otras jurisdicciones, como Estados Unidos, la protección se otorga a obras creadas por personas. Por ello, el contenido generado íntegramente por IA puede no ser susceptible de registro ni de protección por derechos de autor, y Pawwer no garantiza su exclusividad. Las aportaciones creativas humanas (edición sustancial, selección, combinación o integración en una obra mayor) pueden sí ser protegibles. El usuario es responsable de revisar el contenido generado antes de publicarlo y de verificar que no infrinja derechos de terceros, marcas o normas publicitarias aplicables.",
    landing: "Algunas imágenes de este sitio fueron generadas con inteligencia artificial y son ilustrativas.",
    landingAll: "Las imágenes de este sitio fueron creadas con Pawwer, usando inteligencia artificial. Son ilustrativas y no representan clientes, personas ni propiedades reales.",
    more: "Más información", understood: "Entendido", badge: "IA", created: "Creada con Pawwer", illustrative: "Imagen ilustrativa · Creada con Pawwer",
    gallery: "Generados por Pawwer", cta: "Genera tu publicidad ahora mismo", privacy: "Aviso de Privacidad",
  },
  en: {
    title: "AI-generated content and copyright",
    short: "Generated with AI. Content created entirely by AI may not be protected by copyright. Review it before publishing.",
    long: "AI-generated content. Pawwer uses AI tools to generate text, images and videos. Under copyright law in Mexico and other jurisdictions, including the United States, protection is granted to works created by people. Content generated entirely by AI may therefore be ineligible for registration or copyright protection, and Pawwer does not guarantee exclusivity. Human creative contributions (substantial editing, selection, arrangement or integration into a larger work) may be eligible for protection. Users are responsible for reviewing generated content before publishing and verifying that it does not infringe third-party rights, trademarks or applicable advertising rules.",
    landing: "Some images on this site were generated with artificial intelligence and are illustrative.",
    landingAll: "The images on this site were created with Pawwer using artificial intelligence. They are illustrative and do not depict real customers, people or properties.",
    more: "Learn more", understood: "Got it", badge: "AI", created: "Created with Pawwer", illustrative: "Illustrative image · Created with Pawwer",
    gallery: "Generated by Pawwer", cta: "Create your advertising now", privacy: "Privacy Notice",
  },
};
