import { ArrowUpRight, Check, CalendarDays, ChartNoAxesCombined, MessageSquare, Target } from 'lucide-react';
import { Header, HeroMedia, Footer } from './site-ui';
import { plans, contact } from './site-content';

export default function Home(){return <><Header/><main id="contenido">
<section className="hero"><HeroMedia/><div className="hero-shade"/><div className="hero-content wrap"><p className="hero-kicker"><span/> CRM comercial y marketing</p><h1>Data makes<br/>momentum.</h1><p className="hero-es">Tus leads ya están hablando. PAWWER convierte cada conversación en contexto, cada contexto en acción.</p><div className="actions"><a className="button primary" href={contact.trial}>Construye tu sistema <ArrowUpRight size={18}/></a><a className="text-link light" href="#soluciones">Explorar el proceso <span>↓</span></a></div></div><div className="hero-bottom wrap"><span>Scroll to explore</span><span className="hero-rule"/><span>CRM / Marketing / Follow-up</span></div></section>
<section className="chapter-intro"><div className="wrap"><p className="section-label">PAWWER para equipos en movimiento</p><h2>Cuando todo lo que<br/>importa está conectado.</h2><p>Una sola lectura de tu operación comercial: captas, atiendes, conviertes y mides sin perder el hilo.</p></div></section>
<section id="soluciones" className="section wrap solutions"><div className="section-heading"><p className="section-label">Explore our process</p><h2>De la primera señal<br/>al siguiente paso.</h2></div><div className="phase-strip"><span><b>01</b> Captar</span><span><b>02</b> Entender</span><span><b>03</b> Atender</span><span><b>04</b> Convertir</span><span><b>05</b> Medir</span></div><div className="solution-layout"><div className="solution-copy"><article><MessageSquare/><div><h3>Atiende con contexto</h3><p>Leads, contactos y seguimiento en un mismo lugar para que cada conversación tenga continuidad.</p></div></article><article><CalendarDays/><div><h3>Convierte interés en acción</h3><p>Relaciona tu calendario con el seguimiento y da a cada oportunidad un próximo paso.</p></div></article><article><ChartNoAxesCombined/><div><h3>Mide lo que mueve al equipo</h3><p>Origen, resultados y analítica operativa para decidir dónde invertir energía.</p></div></article></div><div className="product-window"><div className="window-bar"><span className="mini-brand">pawwer<span>✳</span></span><span>Commercial operating system</span><span className="avatar">P</span></div><div className="window-body"><p className="window-eyebrow">Today · 09:42</p><h3>The next step is clear.</h3><div className="pipeline">{['Nuevo lead','En seguimiento','Propuesta'].map((stage,i)=><div key={stage}><span className={'stage s'+i}><i/>{stage}</span><div className={'lead '+(i===1?'featured':'')}><span className="lead-icon">{['AC','LM','SR'][i]}</span><strong>{['Andrea C.','Luis M.','Sofía R.'][i]}</strong><small>{['Consulta de servicio','Propuesta en revisión','Proyecto comercial'][i]}</small><p>{i===1?'Cita agendada':'Próximo paso definido'}</p></div></div>)}</div><div className="context-strip"><Check size={16}/> Un historial para dar continuidad.</div></div><p className="mock-caption">Vista conceptual · datos ficticios</p></div></div></section>
<section id="beneficios" className="benefits"><div className="wrap"><p className="section-label">The operating layer</p><h2>Menos memoria.<br/>Más momentum.</h2><div className="benefit-grid"><article><Target/><h3>Un lugar para cada lead</h3><p>Centraliza contactos y oportunidades para trabajar con una visión compartida.</p></article><article><CalendarDays/><h3>Un próximo paso claro</h3><p>Conecta citas y seguimiento para mantener el ritmo comercial.</p></article><article><ChartNoAxesCombined/><h3>Una lectura medible</h3><p>Entiende qué funciona y qué necesita atención desde Crecimiento y Escala.</p></article></div></div></section>
<section id="planes" className="section wrap pricing"><div className="section-heading"><p className="section-label">Plans & pricing</p><h2>Choose the pace<br/>of your growth.</h2><p>7 días sin cargo con acceso temporal al nivel Escala. Mensualidades en pesos mexicanos.</p></div><div className="plans">{plans.map(plan=><article className={'plan '+(plan.name==='Crecimiento'?'highlight':'')} key={plan.name}>{plan.name==='Crecimiento'&&<span className="plan-banner">Most popular</span>}<h3>{plan.name}</h3><p className="plan-summary">{plan.summary}</p><div className="price">{plan.price}<span>MXN / mes</span></div><a href={contact.plan(plan.name)} className={'button '+(plan.name==='Crecimiento'?'primary':'outline')}>Get started <ArrowUpRight size={15}/></a><p className="includes">{plan.inherits}</p><ul>{plan.features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul>{plan.note&&<p className="activation"><span>En activación</span> {plan.note}</p>}</article>)}</div><div className="agency"><div><p className="section-label">PAWWER Agencia</p><h3>El sistema y el equipo<br/>para hacerlo crecer.</h3><p>Todo Escala más estrategia, contenido, pauta, operación y acompañamiento de PAWWER / Creativo Coyote MKT.</p></div><a className="button dark" href={contact.agency}>Solicitar propuesta <ArrowUpRight size={17}/></a></div><div className="pricing-notes"><p><strong>La mensualidad cubre PAWWER.</strong> No incluye inversión publicitaria, cargos de Meta, Google o TikTok, números, SMS, plantillas de WhatsApp, consumo de mensajería ni servicios de terceros.</p><p>No se capturan tarjetas dentro de PAWWER. El cobro se habilitará mediante checkout alojado.</p></div></section>
<section id="contacto" className="contact-section"><div className="wrap contact-grid"><div><p className="section-label">Start building with us</p><h2>Haz que cada<br/>lead avance.</h2><a href={contact.trial} className="button primary">Solicitar prueba de 7 días <ArrowUpRight size={18}/></a></div><div className="contact-details"><a href="mailto:cuentamelo@pawwerapp.com">cuentamelo@pawwerapp.com <ArrowUpRight size={17}/></a><a href="tel:+526678002000">667 800 2000 <ArrowUpRight size={17}/></a><address>Torre B, Blvd. Pedro Infante 2550-Piso 1,<br/>Los Álamos, 80100 Culiacán Rosales, Sin.</address></div></div></section>
</main><Footer/></>}
